[package]
name = "ceserver_rust_api"
version = "0.1.0"
edition = "2018"

[build-dependencies]
cc = "1.0.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"